name: Deploy MOE Content

on:
  push:
    branches:
      - MOE

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: MOE
      
    # Add build steps if you need to compile or build your project.
    # For example, if you're using Node.js you would add:
    # - name: Build the project
    #   run: |
    #     npm install
    #     npm run build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./public
        publish_branch: gh-pages
        destination_dir: MOE
